export const requestType = {
  POST: "post",
  GET: "get",
  PUT: "put",
  DELETE: "delete",
};

export const endPoints = {
    loginAdmin:"loginAdmin",
    getAllOrginization:"getAllOrginization",
    getAllUsers:"getAllUsers",
    updateOrginizationStatus:"updateOrginizationStatus",
    changePasswordAdmin:"changePasswordAdmin",
    getOrginizationById:"getOrginizationById",
    getSubscriptionPlanById:"getSubscriptionPlanById",
    adminDashboard:"adminDashboard",
    // createAllergyCategory:"createAllergyCategory",
    // getAllergiesCategories:"getAllergiesCategories",
    // updateAllergyCategory:"updateAllergyCategory",
    // deleteAllergyCategory:"deleteAllergyCategory",
    // createAllergy:"createAllergy",
    // getAllAllergies:"getAllAllergies",
    // updateAllergy:"updateAllergy",
    // deleteAllergy:"deleteAllergy",
    // getAllMerchants:"getAllMerchants",
    // changePasswordAdmin:"changePasswordAdmin",
    // getAllDrivers:"getAllDrivers",
    // updateMerchantStatus:"updateMerchantStatus",
    // updateDriverStatus:"updateDriverStatus",
    // updateCertificationLink:"updateCertificationLink",
    // getCertificationLink:"getCertificationLink",
    // createCertificationLink:"createCertificationLink",
    // createPerKmCharges:"createPerKmCharges",
    // getPerKmCharges:"getPerKmCharges",
    // upadtePerKmCharges:"upadtePerKmCharges",
    // getSupportMessages:"getSupportMessages",
    // upadteSupportStatus:"upadteSupportStatus",
    // upadteSupportStatus:"upadteSupportStatus",
    // getAllOrders:"getAllOrders",
  // signupRestaurant: "register",
  // loginResturant: "login",
  // addProduct: "addProduct",
  // allProducts: "getProduct",
  // editProduct: "updateProduct",
  // deleteProduct: "deleteProduct",
  // addCategory: "createCategory",
  // editCategory: "updateCategory",
  // deleteCategory: "deleteCategory",
  // getCategories: "getCategory",
  // getPromotions: "getPromo",
  // addPromotion: "createPromo",
  // editPromotion: "updatePromo",
  // deletePromotion: "deletePromo",
  // getResturantProfile: "getRestaurantProfile",
  // editResturantProfile: "updateRestaurantProfile",
  // updateRestaurantStatus: "updateRestaurantStatus",
  // changeRestaurantPassword: "changePassword",
  // getCategoryByAdmin: "getCategoryByAdmin",
  // getAllRestaurants: "getAllRestaurants",
  // updateDeliveryCharges: "updateDeliveryCharges",
  // changePassword: "changePassword",
  // getAdminDetails: "getAdminDetails",
  // getOrderbyRest: "getOrder",
  // restOrderStatusUpdate: "updateOrderStatus",
  // getAllPromotionsByAdmin:"getAllPromo",
};
